version: 0.0
os: linux
files:
    - source: /
      destination: /home/ubuntu/do_it_django_test
file_exists_behavior: OVERWRITE

permissions:
    - object: /home/ubuntu/do_it_djangWo_test
      pattern: '**'
      owner: root
      group: root

hooks:
  AfterInstall:
    - location: scripts/assign_permission.sh
      timeout: 2000
    - location : scripts/after-deploy.sh
      timeout: 10000
      runas: root
